/**
 * scripts/build-prompts.ts
 *
 * Compile-time prompt builder — runs via `predev` and `prebuild` npm scripts.
 * Reads design/system-agents/{name}.md for each system agent, strips the
 * leading human-facing title + blockquote (everything before the first ## heading),
 * and writes the remaining content as a plain exported TypeScript string constant
 * into lib/ai/prompts/generated/{name}.ts.
 *
 * This is the ONLY place that touches design/system-agents/*.md at runtime.
 * Once the app is running, the prompt text is already compiled JS — no filesystem
 * read of design/ ever happens at request time or server start.
 *
 * design/system-agents/*.md is the ONE place system-agent rules are reviewed and
 * edited. The generated files are gitignored and always regenerated fresh.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve } from 'path';

interface AgentSpec {
  /** Source filename stem under design/system-agents/ (no extension) */
  file: string;
  /** Name of the exported TypeScript constant */
  constName: string;
}

const AGENTS: AgentSpec[] = [
  { file: 'import-converter', constName: 'IMPORT_CONVERTER_PROMPT' },
  { file: 'chat-mediator',    constName: 'CHAT_MEDIATOR_PROMPT' },
];

/**
 * Strips the leading title line and any `>` blockquote lines that precede the
 * first `##` heading. Everything from the first `##` onward is prompt content.
 *
 * Throws if no `##` heading is found — this would mean the source file was
 * restructured in a way that would silently deliver an empty prompt.
 */
function extractPromptContent(markdown: string, sourcePath: string): string {
  const lines = markdown.split('\n');
  const firstH2Index = lines.findIndex((line) => /^## /.test(line));

  if (firstH2Index === -1) {
    throw new Error(
      `[build-prompts] No ## heading found in "${sourcePath}". ` +
        'The source file must have at least one ## section for the prompt content.',
    );
  }

  return lines.slice(firstH2Index).join('\n').trimEnd();
}

function main(): void {
  const generatedDir = resolve('lib/ai/prompts/generated');
  mkdirSync(generatedDir, { recursive: true });

  for (const agent of AGENTS) {
    const sourcePath = resolve(`design/system-agents/${agent.file}.md`);
    let markdown: string;

    try {
      markdown = readFileSync(sourcePath, 'utf-8');
    } catch (err) {
      throw new Error(
        `[build-prompts] Cannot read "${sourcePath}": ${(err as Error).message}`,
      );
    }

    const promptContent = extractPromptContent(markdown, sourcePath);

    const outputContent = [
      `// AUTO-GENERATED by scripts/build-prompts.ts — do not edit by hand.`,
      `// Source: design/system-agents/${agent.file}.md`,
      `// Regenerated on every \`npm run dev\` / \`npm run build\`.`,
      `// To change the prompt, edit the source .md file and restart the dev server.`,
      ``,
      `export const ${agent.constName} = ${JSON.stringify(promptContent)};`,
      ``,
    ].join('\n');

    const outputPath = resolve(`lib/ai/prompts/generated/${agent.file}.ts`);
    writeFileSync(outputPath, outputContent, 'utf-8');
    console.log(`[build-prompts] Generated: ${outputPath}`);
  }

  console.log('[build-prompts] Done.');
}

main();
