/**
 * scripts/build-prompts.ts
 *
 * Compile-time prompt builder — runs via `predev` and `prebuild` npm scripts.
 * Reads lib/ai/prompts/system-agents/{name}.md for each system agent, strips the
 * leading human-facing title + blockquote (everything before the first ## heading),
 * and writes the remaining content as a plain exported TypeScript string constant
 * into lib/ai/prompts/generated/{name}.ts.
 *
 * This is the ONLY place that touches lib/ai/prompts/system-agents/*.md at runtime.
 * Once the app is running, the prompt text is already compiled JS — no filesystem
 * read of the source .md files ever happens at request time or server start.
 *
 * lib/ai/prompts/system-agents/*.md is the ONE place system-agent rules are reviewed
 * and edited — moved here from design/system-agents/ (2026-07-29) because this content
 * is source code compiled into the running app, not passive documentation; it now sits
 * next to the generated/ output it produces. The generated files are gitignored and
 * always regenerated fresh.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve } from 'path';

interface AgentSpec {
  /** Source filename stem under lib/ai/prompts/system-agents/ (no extension) */
  file: string;
  /** Name of the exported TypeScript constant */
  constName: string;
}

const AGENTS: AgentSpec[] = [
  { file: 'hermes',    constName: 'HERMES_PROMPT' },
  { file: 'daedalus',  constName: 'DAEDALUS_PROMPT' },
  { file: 'prometheus', constName: 'PROMETHEUS_PROMPT' },
];

/**
 * Extracts the prompt content from a source file, supporting two conventions:
 *
 *   1. Real-agent format (YAML frontmatter): `---\n...\n---\n` followed by the
 *      system prompt body, verbatim — same split as a real Claude Code subagent
 *      file (architecture/Agent-Full-Reference.md). Everything after the closing
 *      `---` is the prompt, unmodified.
 *   2. Legacy format: a leading `# Title` line with content starting at the first
 *      `##` heading. Everything before that first `##` is stripped.
 *
 * Throws if a file matches neither shape — that would mean the source file was
 * restructured in a way that would silently deliver an empty prompt.
 */
function extractPromptContent(markdown: string, sourcePath: string): string {
  const lines = markdown.split('\n');

  // Real-agent format: leading `---` frontmatter block.
  if (lines[0]?.trim() === '---') {
    const closingOffset = lines.slice(1).findIndex((line) => line.trim() === '---');
    if (closingOffset === -1) {
      throw new Error(
        `[build-prompts] Unterminated frontmatter in "${sourcePath}" — found an ` +
          'opening "---" with no matching closing "---".',
      );
    }
    const bodyStart = closingOffset + 2; // skip the opening `---` and the closing `---`
    return lines.slice(bodyStart).join('\n').trim();
  }

  // Legacy format: strip everything before the first `##` heading.
  const firstH2Index = lines.findIndex((line) => /^## /.test(line));

  if (firstH2Index === -1) {
    throw new Error(
      `[build-prompts] No ## heading found in "${sourcePath}". ` +
        'The source file must have either a leading YAML frontmatter block or at ' +
        'least one ## section for the prompt content.',
    );
  }

  return lines.slice(firstH2Index).join('\n').trimEnd();
}

function main(): void {
  const generatedDir = resolve('lib/ai/prompts/generated');
  mkdirSync(generatedDir, { recursive: true });

  for (const agent of AGENTS) {
    const sourcePath = resolve(`lib/ai/prompts/system-agents/${agent.file}.md`);
    let markdown: string;

    try {
      markdown = readFileSync(sourcePath, 'utf-8');
    } catch (err) {
      throw new Error(
        `[build-prompts] Cannot read "${sourcePath}": ${(err as Error).message}`,
      );
    }

    const promptContent = extractPromptContent(markdown, sourcePath);

    const outputContent = [
      `// AUTO-GENERATED by scripts/build-prompts.ts — do not edit by hand.`,
      `// Source: lib/ai/prompts/system-agents/${agent.file}.md`,
      `// Regenerated on every \`npm run dev\` / \`npm run build\`.`,
      `// To change the prompt, edit the source .md file and restart the dev server.`,
      ``,
      `export const ${agent.constName} = ${JSON.stringify(promptContent)};`,
      ``,
    ].join('\n');

    const outputPath = resolve(`lib/ai/prompts/generated/${agent.file}.ts`);
    writeFileSync(outputPath, outputContent, 'utf-8');
    console.log(`[build-prompts] Generated: ${outputPath}`);
  }

  console.log('[build-prompts] Done.');
}

main();
